image: alpine:latest

stages:
  - deploy
  - mirror

variables:
  GIT_STRATEGY: fetch
  NODE_ENV: production

# Despliegue a Netlify
deploy_to_netlify:
  stage: deploy
  image: node:latest
  script:
    - npm install -g netlify-cli
    - echo "Escribiendo netlify.toml..."
    - echo "Testing the double push"
    - echo -e "[build]\n  publish = \".\"\n\n[site]\n  id = \"$NETLIFY_SITE_ID\"" > netlify.toml
    - netlify deploy --prod --dir=. --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
  only:
    - main